### ISSUE TITLE
The "use diesel::*" change causes breakage as this can have conflicts with database table names

### ISSUE THREAD

**Issue by longsleep** [Wulf/dsync#116]
With https://github.com/Wulf/dsync/commit/5062ebe1d1e0ede5ee1865a0249c6f6f57bcd074 the previous `use crate::diesel::*;` was changed `to use diesel::*`. While this is fine in general, this import is too "wide" if by chance a database table matches one of the very many imports which are pulled in from this.

Please revert this change.

In my example, there is a table named `associations` which is not super uncommon.

Having the import from `crate::diesel::*` allows manual defines of the actually needed diesel imports. Maybe it is even better to avoid the wildcard import altogether.

```rust
pub(crate) mod diesel {
    // NOTE(longsleep): This module wrapps the diesel crate exports so that
    // it does not export "associations" as that conflicts with our database
    // table "associations".
    pub use diesel::{
        backend, deserialize, dsl, expression, insert_into, insertable, internal, prelude, query_builder, row,
        AsChangeset, ExpressionMethods, Insertable, QueryDsl, Queryable, RunQueryDsl, Selectable,
    };
}
```

**Comment by hasezoey** [comment]
i agree that the import is too wide, but currently our implementation is doing imports first then the table then the functions, so we would likely need to refactor some more stuff for that.

i will revert it for now (by putting in a PR)
