### ISSUE TITLE
Add support for "unsigned" numeric fields

### ISSUE THREAD

**Issue by longsleep** [Wulf/dsync#12]
Hi, I just gave this project a try to generate DB models for an existing database. The database uses unsigned integers on may columns. Those get typed (for example) as `i32` where it should be `u32`. 

I came accross https://github.com/Wulf/dsync/blob/12979e00998635291ecaf721cf6bc4282d9808ee/src/parser.rs (but there is no panic, or message visible when running `dsync`.

The resulting problem is, that all models fail to derive `Insertable` and `AsChangeset`.

```
trait bound `i32: diesel::Expression` is not satisfied
```

For example this table
```rust
diesel::table! {
    aliases (id) {
        id -> Unsigned<Integer>,
        aliasname -> Varchar,
        mainname -> Varchar,
    }
}
```

yields with dsync:

```rust
#[derive(Debug, Serialize, Deserialize, Clone, Queryable, Insertable, AsChangeset, Identifiable)]
#[diesel(table_name=aliases, primary_key(id))]
pub struct Aliase {
    pub id: i32,
    pub aliasname: String,
    pub mainname: String,
}
```

And with https://github.com/abbychau/diesel_cli_ext (where it works):

```rust
#[derive(Debug, Serialize, Deserialize, Clone, Queryable, Insertable, AsChangeset, Identifiable)]
#[diesel(table_name = aliases)]
pub struct Aliase {
    pub id: u32,
    pub aliasname: String,
    pub mainname: String,
}
```

**Comment by Wulf** [comment]
hey @longsleep, hope things are well -- thanks for your request and showing examples. Sorry it took so long to get this out.

`0.0.10` should have this fixed :-)

**Comment by Wulf** [comment]
Closing, feel free to reopen if you encounter any issues!
