### ISSUE TITLE
error[E0277]: the trait bound `Pg: LoadConnection` is not satisfied | generated CRUD from dsync

### ISSUE THREAD

**Issue by SamuelMarks** [Wulf/dsync#143]
I've commented out everything CRUD in the meantime: https://github.com/SamuelMarks/rust-actix-diesel-auth-scaffold/blob/0c067e5/src/models/users.rs#L84

Would appreciate any tips on how to resolve this issue

**Comment by hasezoey** [comment]
Please provide more information as to what dsync version, rust version you are using and where the error happens (stacktrace).

If possible, you can also add a new test to cover this case in the future.

**Comment by SamuelMarks** [comment]
```
rustc 1.85.0-nightly (7442931d4 2024-11-30)
diesel = { version = "^2.2", features = ["postgres", "r2d2", "serde_json"] }
```
dsync @ d307512 (at least 0.1.0)


The error happens, for example, here:
```rs
impl Users {
    /// Insert a new row into `users` with a given [`CreateUsers`]
    pub fn create(db: &mut ConnectionType, item: &CreateUsers) -> diesel::QueryResult<Self> {
        use crate::schema::users::dsl::*;

        diesel::insert_into(users)
            .values(item)
            .get_result::<Self>(db)
    }
}
```
https://github.com/SamuelMarks/rust-actix-diesel-auth-scaffold/blob/0c067e5/src/models/users.rs#L84 (comment out that first function)

```rs
error[E0277]: the trait bound `Pg: LoadConnection` is not satisfied
    --> src/models/users.rs:91:33
     |
91   |             .get_result::<Self>(db)
     |              ----------         ^^ the trait `LoadConnection` is not implemented for `Pg`
     |              |
     |              required by a bound introduced by this call
     |
     = help: the following other types implement trait `LoadConnection<B>`:
               PooledConnection<M>
               diesel::PgConnection
     = note: required for `InsertStatement<table, ValuesClause<(..., ..., ...), ...>>` to implement `LoadQuery<'_, Pg, Users>`
note: required by a bound in `get_result`
    --> diesel-2.2.5/src/query_dsl/mod.rs:1722:15
     |
1720 |     fn get_result<'query, U>(self, conn: &mut Conn) -> QueryResult<U>
     |        ---------- required by a bound in this associated function
1721 |     where
1722 |         Self: LoadQuery<'query, Conn, U>,
     |               ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `RunQueryDsl::get_result`
```

**Comment by hasezoey** [comment]
If i understand that error correctly, you need to replace `ConnectionType`(`--connection-type`) with `diesel::pg::PgConnection`

**Comment by SamuelMarks** [comment]
Ohhhhhhh

Thanks

A bit of validation when an incorrect one is provided wouldn't go astray…

**Comment by hasezoey** [comment]
> A bit of validation when an incorrect one is provided wouldn't go astray…

to my knowledge diesel supports third-party connections, so we cant 100% check it (though i guess we *could* for prefix `diesel::`); also all known / common ones are listed in dsync help.
