### ISSUE TITLE
Dsync not working with schema generated by diesel 2.1.0

### ISSUE THREAD

**Issue by fox91** [Wulf/dsync#49]
My `schema.rs` generated by diesel `2.0.4` worked fine. 
Now I've upgraded to diesel [`2.1.0`](https://github.com/diesel-rs/diesel/blob/v2.1.0/CHANGELOG.md) which, on top of everything else, added support for column size restrictions (aka `max_length`) and `dsync` panic with `Unsupported schema format! (Invalid column definition token in diesel table macro)`.

**Comment by kerzeld** [comment]
Same problem for me.
Diesel now takes the max_length into the table macros like this:
`#[max_length = 16]`

After removing these annotations dsync works again.

**Comment by jimmy-ho** [comment]
I've added a patch with https://github.com/Wulf/dsync/pull/51 that appears to be functional with the schema I have.
