### ISSUE TITLE
Option to not generate with `serde`

### ISSUE THREAD

**Issue by hasezoey** [Wulf/dsync#52]
My project does not use `serde` (at least yet), so it would be great to have a option to disable generating with `serde::` types

example:

```rust
use serde::{Deserialize, Serialize};

//                 v            v
#[derive(Debug, Serialize, Deserialize, Clone, Queryable, Insertable, AsChangeset, Selectable)]
```

**Comment by Wulf** [comment]
hey @hasezoey, thanks for suggesting this and creating a PR for the feature. I've published 0.0.15 now with your changes.

In the future, I think I'd like to make this the default
