### ISSUE TITLE
Option to set sql schema and model path

### ISSUE THREAD

**Issue by hasezoey** [Wulf/dsync#53]
Currently dsync automatically adds a static `use crate::schema::*` and `use crate::models::`, which may not be the path where the sql schemas and models are at.

for example i run `dsync -i src/data/sql_schema.rs  -o src/data/models --connection-type "diesel::SqliteConnection"` and so would need something like `use crate::data::sql_schema;` so a option to set that like `connection-type` would be great

example:
```sh
dsync -i src/data/sql_schema.rs  -o src/data/models --connection-type "diesel::SqliteConnection" --sql-schema-path "crate::data::sql_schema" --sql-model-path "crate::data::models::"
```

**Comment by Wulf** [comment]
@hasezoey, again, thanks for suggesting this change and creating a PR for it. `0.0.16` should have this change!
