### ISSUE TITLE
fix: incomplete generated code for pk

### ISSUE THREAD

**Issue by jjangga0214** [Wulf/dsync#90]
<img width="529" alt="스크린샷 2023-10-16 오후 12 58 41" src="https://github.com/Wulf/dsync/assets/28584151/cb790283-369d-452a-93d3-2074235fb1fb">

As we can see, part of using primary key is missing. 

INFO

- dsync: 0.0.16
- diesel: 2.1.3
- rustc: 1.70.0 (90c541806 2023-05-31)
- OS: macOS Ventura 13.5.2(22G91) 
- HW: M1 MAX

**Comment by jjangga0214** [comment]
Never mind. I missed specifying pk from `diesel::table!`

But I still think it'd be good to print out "[ERROR] You're missing primary key!" from CLI output.

**Comment by hasezoey** [comment]
could you provide a example diesel table that produces this problem?
