### ISSUE TITLE
fix: allow optional `GenerationConfig` fields

### ISSUE THREAD

**Issue by jjangga0214** [Wulf/dsync#92]
The README guides creating custom bin like this.

```rs
use std::{collections::HashMap, path::PathBuf};
use dsync::{GenerationConfig, TableOptions};

pub fn main() {
    let dir = env!("CARGO_MANIFEST_DIR");

    dsync::generate_files(
        PathBuf::from_iter([dir, "src/schema.rs"]), 
        PathBuf::from_iter([dir, "src/models"]), 
        GenerationConfig { /* ... your generation options ... */ }
    );
}
```

https://github.com/Wulf/dsync/blob/007ace83c139f67e1d85ed4829cf0b6953d121df/src/lib.rs#L216-L237

I wanted to only specify `GenerationConfig.connection_type`, but I am forced to input every options.
I think they should be able to be omitted except `connection_type`.

Thank you very much for this precious project.

**Comment by hasezoey** [comment]
>  I think they should be able to be omitted except connection_type.

the problem with `Default` is that you can either: 
- not implement it and must provide every option
- implement it and provide a default for every option

to my knowledge there is no in-between, but i guess we could add a builder method

**Comment by Wulf** [comment]
You can do this :)

`GenerationConfig { override: true, ...Default::default() }`

Maybe we can update the example in the README?

**Comment by hasezoey** [comment]
i have thought about this for a bit. this could be achieved in multiple ways, but i am unsure which to take:

1. the simplest option of all fields having a default (including `connection_type`)
  ```rust
GenerationConfig { ..Default::default() }
GenerationConfig {
	connection_type: "something else"
	..Default::default() 
}
  ```
2. the second simplest option of all fields having a default, but `connection_type` is empty and errors at runtime
  ```rust
GenerationConfig { ..Default::default() } // Error at runtime

GenerationConfig {
	connection_type: "something else"
	..Default::default() 
}
  ```
3. move all non-required (defaultable) fields into their own struct as a subfield
  ```rust
GenerationConfig {
	connection_type: "something else"
	subfields: SomeName { // or directly Default::default()
		..Default::default()
	}
}
  ```

i am personally against erroring at runtime and somewhat against `connection_type` having a default.

(using the builder pattern would also be a option, but i didnt list it because it is quite verbose)

any other suggestions?

**Comment by Wulf** [comment]
I agree, we should be treating required and optional fields differently. Which part of the builder pattern do you feel is verbose?

For example, I don't think this is so bad:
```
GenerationConfig::new(required1, required2, ...)
  .optional1(..)
  .optional2(..)
```

I like this more than writing `...Default::default()`

**Comment by Wulf** [comment]
ah okay, understood. I can see why you like the approach in point 3 :)

What if we split the required and optional structs entirely?

```rust
GenerationConfig {
  // required fields
}

GenerationOptions {
  // optional fields, all of these have sane defaults
}
```

Then we can pass this in directly into the library's main fn:
```rust
dsync::generate_files(
  input, 
  output, 
  // here are the required args:
  GenerationConfig {},
  // here are the optional args:
  Default::default()
)
```

Perhaps this way we can also move `input` and `output` into the config struct

**Comment by Wulf** [comment]
ah okay! I'm in favour of the third approach you outlined above (point 3) but ultimately, I'll leave the decision to you :)

Also, if you do want to go that route, could I suggest we name it `opts` or `options` instead of `optional`?

Thanks again for exploring this in a detailed manner!

**Comment by hasezoey** [comment]
> Also, if you do want to go that route, could I suggest we name it opts or options instead of optional?

sure will make a test PR and then we will see if it is a good approach and what can be changed
