### ISSUE TITLE
question: `belonging_to`

### ISSUE THREAD

**Issue by jjangga0214** [Wulf/dsync#95]
It seems `belonging_to` is not supported.
Is this true?

**Comment by hasezoey** [comment]
i dont know what this is about, please expand your issue with the diesel schema and what you expect as output

**Comment by hasezoey** [comment]
did you import the `BelongingToDsl` trait? (importing it is required to be able to use its functions)

**Comment by jjangga0214** [comment]
Yes, by `use diesel::prelude::*;`.

**Comment by hasezoey** [comment]
then i dont think i can help too much, because i have not used that functionality yet, and the dsync tests are not in the best of states (they are currently only hand checked, but not checked that they actually compile and / or run)

**Comment by jjangga0214** [comment]
Thank you!
I left a discussion from diesel's side.
Here a [link](https://github.com/diesel-rs/diesel/discussions/3830) is for folks who may come later.

**Comment by Wulf** [comment]
@hasezoey thanks for jumping on these issues!

@jjangga0214 I've used the generated belonging_to successfully in the past. Try following through with this example, you might be able to catch something specific:
https://github.com/diesel-rs/diesel/tree/2.1.x/examples/postgres/relations
