### ISSUE TITLE
feat: support `#[derive(QueryableByName)]`

### ISSUE THREAD

**Issue by jjangga0214** [Wulf/dsync#97]
Hi!

I'd like to suggest to support [QueryableByName](https://docs.diesel.rs/master/diesel/deserialize/derive.QueryableByName.html) derive.

This is useful for using `sql_query`.

How do you think?

**Comment by hasezoey** [comment]
to my understanding this derive needs to be added to the Read Struct (not Update or Create) and can be applied to all Read Structs (no special conditions, like `Associations` needs foreign_keys?)

**Comment by Wulf** [comment]
@jjangga0214 thanks for the suggestion and I agree @hasezoey, this is something we'd add to the Read struct. I don't see any harm in adding this. We should feature-gate this as it might increase compilation times, but have it included as part of the default feature set?
